spring:
  application:
    name: spring-openai-demo

  ai:
    openai:
      api-key : ${OPEN_API_KEY}
    ollama:
      base-url:http://localhost:11434/
    chat:
      model:llama3.2:1b
server:
  port: 9292

