spring:
  application:
    name: spring-openai-demo

  ai:
    openai:
      api-key: ${OPEN_API_KEY}
#    ollama:
#      base-url: http://localhost:11434
#      chat:
#        model: llama32
#    chat:
#      client:
#        enabled: false
logging:
  level:
    org.springframework.ai.ollama: DEBUG
    org.springframework.web.client: DEBUG

server:
  port: 9292